server:
  port: 8080

spring:
  application:
    name: Easy-Pass

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID_CLIENT}
            client-secret: ${GOOGLE_SECRET_CLIENT}
#          facebook:
#           client-id: FACEBOOK_CLIENT_ID
#           client-secret: FACEBOOK_CLIENT_SECRET
#          github:
#           client-id: GITHUB_CLIENT_ID
#           client-secret: GITHUB_CLIENT_SECRET
logging:
  level:
    org:
      springframework:
        security: TRACE